### ISSUE TITLE
bug in writers

### ISSUE THREAD

**Issue by erickpeirson** [diging/tethne#14]
```
>>> import tethne.writers as wr

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tethne/writers/__init__.py", line 7, in <module>
    import tethne.writers.collection
  File "tethne/writers/collection.py", line 88
    for i in sorted(nodes[n].keys()):
                                    ^
SyntaxError: invalid syntax
```

**Comment by erickpeirson** [comment]
fixed in [v0.3.0-alpha](https://github.com/diging/tethne/tree/v0.3.0-alpha)
