### ISSUE TITLE
Import tethne.writers

### ISSUE THREAD

**Issue by deryc** [diging/tethne#17]
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    import tethne.writers as wr
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tethne/writers/**init**.py", line 7, in <module>
    import tethne.writers.collection
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tethne/writers/collection.py", line 88
    for i in sorted(nodes[n].keys()):

**Comment by erickpeirson** [comment]
Looks like a bug in one of the previous versions; try installing the latest release (v0.3.1-alpha). Be sure to uninstall the old version first. Let me know if it still gives the error with the new version.
