### ISSUE TITLE
Tethne Install Error setup.py egg_info

### ISSUE THREAD

**Issue by adil1993** [diging/tethne#178]
I am getting error while installing tethne through pip 

Collecting distribute (from slate->tethne)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7_/0psy1jvd4jjd3ckc7btqc4cr0000gn/T/pip-build-d5l2l4t1/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/7_/0psy1jvd4jjd3ckc7btqc4cr0000gn/T/pip-build-d5l2l4t1/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/7_/0psy1jvd4jjd3ckc7btqc4cr0000gn/T/pip-build-d5l2l4t1/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/7_/0psy1jvd4jjd3ckc7btqc4cr0000gn/T/pip-build-d5l2l4t1/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/7_/0psy1jvd4jjd3ckc7btqc4cr0000gn/T/pip-build-d5l2l4t1/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/7_/0psy1jvd4jjd3ckc7btqc4cr0000gn/T/pip-build-d5l2l4t1/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by sshojiro** [comment]
@adil1993 I have encountered the same error and am still working on fixing it.
I thought `pip install python-dotenv` was helpful, as a similar discussion mentions: https://github.com/theskumar/python-dotenv/issues/113#issue-324759355.
However, I couldn't fix this. The cause seems in `pip install distribute`. When you may find a way to solve, I would appreciate it to share it with me. Thank you in advance.

**Comment by jdamerow** [comment]
@adil1993 and @sshojiro, are you using Python 3 by any chance? It's not fully supported I believe. I did get your error when I ran ```pip3 install tethne```. Installing the development version seemed to work fine though ```pip3 install tethne --pre```.

**Comment by sshojiro** [comment]
@jdamerow 
Wow thank you for your comment, it was a great help to me and it worked! I'm looking forward to a stable version of the library for python3.
