### ISSUE TITLE
ValueError when building bibliographic coupling graph with threshold == 2

### ISSUE THREAD

**Issue by erickpeirson** [diging/tethne#18]
Using TethneGUI, downloaded Feb 27 @ 1pm. MacOSX.

```
----------------------------------------
    Workflow step: Graph
----------------------------------------
Loading DataCollection with slices from /Users/Bianca/Desktop/PMS Tethne/tmp_DST1315262543/DST1315262543_DataCollection_sliced.pickle...done.
Using first slice in DataCollection: date.

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Bianca/Downloads/TethneGUI-2/configuration/org.eclipse.osgi/bundles/2/1/.cp/python/tethne/__main__.py", line 403, in <module>
    kwargs['threshold'] = int(options.threshold)
ValueError: invalid literal for int() with base 10: '2.0'
```

**Comment by erickpeirson** [comment]
Fixed in [TethneGUI 0.3](http://sourceforge.net/projects/neotomaphenax/files/)
