### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by lowspace** [diging/tethne#182]
I tried two ways, pip and git, to install tethne, but all failed and throw the same error:
```
    ERROR: Command errored out with exit status 1:
     command: /Users/dnhb/opt/anaconda3/envs/wos/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setup.py'"'"'; __file__='"'"'/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/pip-egg-info
         cwd: /private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/zt/br8fkpx52gl87ltrz_3731mh0000gn/T/pip-install-3o1swz2u/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by lowspace** [comment]
I have somewhat solved this issue by using Pycharm to install.

**Comment by jeffcsauer** [comment]
Bump - can't install using pip July 2021

**Comment by mhaeussermann** [comment]
> Bump - can't install using pip July 2021

The latest release is not Python 3 compatible, it seems. Using `pip install git+https://github.com/diging/tethne` works.

**Comment by serenalotreck** [comment]
> pip install git+https://github.com/diging/tethne

THANK YOU @mhaeussermann !! Going to post this to the Google Group, as it looks like folks there haven't gotten this answer yet.
