### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mubashirqasim** [diging/tethne#63]
Hi Eric, 

I am processing JSTOR DFR dataset of 5000 papers using the following code:

MyManager = MALLETModelManager(MyCorpus, feature, outpath, temppath = temp, mallet_path=malletpath)
MyLDAModel = MyManager.build(Z=20, max_iter=300, prep=True)

The same code performs well on a small dataset of 250 papers. However, I am getting the following error with the large dataset. 

Traceback (most recent call last):
  File "/media/mubashir/StudyDrive/temp/Tethne Load some data Linux.py", line 23, in <module>
    MyLDAModel = MyManager.build(Z=20, max_iter=300, prep=True)
  File "/home/mubashir/anaconda/lib/python2.7/site-packages/tethne/model/managers/**init**.py", line 116, in build
    self._load_model()
  File "/home/mubashir/anaconda/lib/python2.7/site-packages/tethne/model/managers/mallet.py", line 230, in _load_model
    self.meta_path  )
  File "/home/mubashir/anaconda/lib/python2.7/site-packages/tethne/model/corpus/ldamodel.py", line 268, in from_mallet
    model = loader.load()
  File "/home/mubashir/anaconda/lib/python2.7/site-packages/tethne/model/corpus/ldamodel.py", line 302, in load
    self._handle_metadata()
  File "/home/mubashir/anaconda/lib/python2.7/site-packages/tethne/model/corpus/ldamodel.py", line 434, in _handle_metadata
    for i in xrange(0, len(l)) }
  File "/home/mubashir/anaconda/lib/python2.7/site-packages/tethne/model/corpus/ldamodel.py", line 434, in <dictcomp>
    for i in xrange(0, len(l)) }
IndexError: list index out of range

Any sort of help is cordially appreciated.

Thanks,

Mubashir

**Comment by erickpeirson** [comment]
This should be corrected in v0.7. Closing for now.
