### ISSUE TITLE
DFR file parsing error (not able to find citations.xml file)

### ISSUE THREAD

**Issue by gkumbhat** [diging/tethne#83]
When we try to load data from dfr files using following command (in python):

```
from tethne.readers import dfr
 papers=dfr.read("/home/gkumbhat/Tethne/Downloads/2015.9.12.t36k3WXD")
```

System is not able to find citations.xml file, because its searching for "citations.XML" file. The default file generated by system is citations.xml. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gkumbhat/Tethne/tethne/tethne/readers/dfr.py", line 217, in read
    parser = DfRParser(os.path.join(path, "citations.XML"))
  File "/home/gkumbhat/Tethne/tethne/tethne/readers/base.py", line 66, in __init__
    super(IterParser, self).__init__(*args, **kwargs)
  File "/home/gkumbhat/Tethne/tethne/tethne/readers/base.py", line 29, in __init__
    self.open()
  File "/home/gkumbhat/Tethne/tethne/tethne/readers/dfr.py", line 31, in open
    with open(self.path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/gkumbhat/Tethne/Downloads/2015.9.12.t36k3WXD/citations.XML'
```

**Comment by erickpeirson** [comment]
This is fixed in pr #94
