### ISSUE TITLE
can not read a wos directory, error shown in the attached pic

### ISSUE THREAD

**Issue by yzou20** [diging/tethne#84]
![screen shot 2015-09-13 at 8 46 44 pm](https://cloud.githubusercontent.com/assets/8672876/9841801/8b133d7a-5a59-11e5-80f3-a2d512034a04.png)

**Comment by gkumbhat** [comment]
I have solved this error by changing the encoding to latin-1 in wos.py at line 130 and 132. I also changed the default format of  data in base.py to string. but while testing the same dataset which ywang used I encountered another error:

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    papers=wos.from_dir(datadir)
  File "/home/gkumbhat/Tethne/tethne/tethne/readers/wos.py", line 251, in from_dir
    return Corpus(papers, *_kwargs)
  File "/home/gkumbhat/Tethne/tethne/tethne/classes/corpus.py", line 149, in **init**
    self.indexed_papers = {self._generate_index(paper): paper for paper in papers}
  File "/home/gkumbhat/Tethne/tethne/tethne/classes/corpus.py", line 149, in <dictcomp>
    self.indexed_papers = {self._generate_index(paper): paper for paper in papers}
  File "/home/gkumbhat/Tethne/tethne/tethne/classes/corpus.py", line 171, in _generate_index
    authors = zip(_paper.authors)[0]
IndexError: list index out of range

I am trying to solve this error now.

**Comment by erickpeirson** [comment]
Glad you're making progress! Be sure to work on one problem at a time. Looks like this is unrelated, so create a new issue for it. And if you work on it, do so in a new branch.

---

Erick Peirson
Postdoctoral Scholar
ASU-SFI Center for Biosocial Complexity
Arizona State University
