### ISSUE TITLE
WOS not able to detect author name in paper

### ISSUE THREAD

**Issue by gkumbhat** [diging/tethne#92]
Occured when trying to run test cases for wos parser on ywang's dataset. 

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    papers=wos.from_dir(datadir)
  File "/home/gkumbhat/Tethne/tethne/tethne/readers/wos.py", line 251, in from_dir
    return Corpus(papers, **kwargs)
  File "/home/gkumbhat/Tethne/tethne/tethne/classes/corpus.py", line 149, in __init__
    self.indexed_papers = {self._generate_index(paper): paper for paper in papers}
  File "/home/gkumbhat/Tethne/tethne/tethne/classes/corpus.py", line 149, in <dictcomp>
    self.indexed_papers = {self._generate_index(paper): paper for paper in papers}
  File "/home/gkumbhat/Tethne/tethne/tethne/classes/corpus.py", line 171, in _generate_index
    authors = zip(*paper.authors)[0]
IndexError: list index out of range
```

**Comment by erickpeirson** [comment]
@gkumbhat What does the author data for this entry look like?
